services:
  db:
    image: postgres:15
    container_name: videostat-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.2.4-management
    container_name: videostat-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  migrate:
    image: migrate/migrate:v4.17.0
    container_name: videostat-migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    entrypoint: [
      "migrate",
      "-path", "/migrations",
      "-database", "${DB_URL_MIGRATE}"
    ]

  buf:
    image: bufbuild/buf:1.66.0
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: ["buf"]

volumes:
  db_data:
  rabbitmq_data:
